import { useState } from 'react'
import { Link } from 'react-router-dom'

function RecommendationPage() {
    const [product, setProduct] = useState('')
    const [submitted, setSubmitted] = useState(false)
    const submit = (event) => { event.preventDefault(); if (product.trim()) setSubmitted(true) }
    return <section className="data-page recommendation-page"><div className="page-intro-row"><div><p className="eyebrow"><span></span> Product to standard</p><h1>Describe what you <em>make.</em></h1><p>We’ll identify potentially relevant Indian Standards and explain what still needs verification.</p></div><span className="flow-step">Step 01 / 02</span></div><div className="recommendation-layout"><form className="recommendation-form" onSubmit={submit}><label>Product description<textarea value={product} onChange={(event) => setProduct(event.target.value)} placeholder="Example: I manufacture stainless steel water bottles for domestic use..." rows="6" required /></label><div className="form-grid"><label>Industry<select><option>Choose industry</option><option>Consumer products</option><option>Electrical</option><option>Automotive</option><option>Construction</option></select></label><label>Material<input placeholder="Optional" /></label></div><button className="button" type="submit">Find potential standards <span>↗</span></button><p className="form-note">Recommendations are evidence-led suggestions, not a compliance verdict.</p></form><aside className="evidence-side"><span className="side-icon">✦</span><h2>What you’ll get</h2><ul><li>Ranked candidate standards</li><li>Why each standard matched</li><li>Certification and testing signals</li><li>Clear verification gaps</li></ul><Link to="/assistant">Need help describing it? Ask standIQ <span>↗</span></Link></aside></div>{submitted && <div className="recommendation-results"><div className="results-meta"><strong>Potential matches</strong><span>Evidence preview for: {product}</span></div><article className="match-card"><div><span className="confidence-badge confidence-medium">Potentially applicable</span><h2>IS 302 (Part 1) — Household electrical appliances</h2><p>Matched because the description suggests a consumer appliance with electrical safety requirements.</p></div><div className="match-side"><span>Medium confidence</span><Link to="/standards">Review standard <span>↗</span></Link></div></article><div className="insufficient-state"><strong>Applicability is not verified yet</strong><p>Product dimensions, material, intended use, and applicable regulations are still needed before a compliance conclusion.</p><Link className="button button-light" to="/assistant">Talk to a consultant <span>↗</span></Link></div></div>}</section>
}

export default RecommendationPage
